# Question 1

(a) 

Implement (write a code) Gaussian Elimination with partial pivoting to solve a linear system $Ax = b$, given as output the coefficients of a nonsingular, $n\times n$ matrix $A$ and an $n$-vector $b$. Your code should produce the solution $x$ or an error message (if $A$ is nonsingular) and the information needed for the $LU$ factorization.

In [1]:
import numpy as np

def ge_pp(A, b):
    """
    solve a linear system Ax = b with the Gaussian Elimination with partial pivoting.
    
    Inputs:
        A: n-by-n matrix
        b: n-vector
    
    Outputs:
        If A is nonsingular, then return (x, P, LU) tuple, where
            x: solution
            P: permutation matrix for partial pivoting
            LU: n-by-n matrix which stores the L and U
        else if A is singular, then return (None, None, None) and print error message
    """
    LU, x = np.array(A, dtype='double'), np.array(b, dtype='double').reshape(-1)
    n = len(x)
    
    # permutation matrix
    P = np.eye(n)
    
    for j in range(n-1):
        
        jm = np.argmax(np.abs(LU[j:,j])) + j  # row index of the pivot
        
        # singular matrix?
        if np.isclose(np.abs(LU[jm,j]), 0):
            print('Input matrix is singular!')
            return (None, None, None)
        
        # exchange row index j and jm 
        if jm != j:
            LU[(jm,j),:] = LU[(j,jm),:]
            x[jm], x[j] = x[j], x[jm]
            P[(jm,j),:] = P[(j,jm),:]

        # gaussian elimination
        for i in range(j+1,n):
            m = LU[i,j]/LU[j,j]
            LU[i,j+1:] = LU[i,j+1:]-m*LU[j,j+1:]
            x[i] =  x[i]-m*x[j]
            LU[i,j] = m
    
    if np.isclose(np.abs(LU[n-1,n-1]),0):
        print('Input matrix is singular!')
        return (None, None, None)
    
    # backward substitution
    for i in range(n-1,-1,-1):
        x[i] = (x[i]-sum(LU[i,i+1:]*x[i+1:]))/LU[i,i]
    
    return x, P, LU

(b) Use your Gaussian Elimination code to solve $Ax = b$, for some $A,b$

In [2]:
# A and b
A = np.array([[5,1,0,2,1],[0,4,0,1,2],[1,1,4,1,1],[0,1,2,6,0],[0,0,1,2,4]])
b = np.array([1,2,3,4,5])

x, P, LU = ge_pp(A,b)

# parse the results
print('the solution is', x)

print('\nthe permutation matrix is')
print(P)

L = np.tril(LU)
L[np.diag_indices_from(LU)] = 1
U = np.triu(LU)
print('\nthe L is')
print(L)
print('\nthe U is')
print(U)

the solution is [-0.17083787 -0.06746464  0.46028292  0.52448313  0.8726877 ]

the permutation matrix is
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

the L is
[[1.         0.         0.         0.         0.        ]
 [0.         1.         0.         0.         0.        ]
 [0.2        0.2        1.         0.         0.        ]
 [0.         0.25       0.5        1.         0.        ]
 [0.         0.         0.25       0.34234234 1.        ]]

the U is
[[ 5.          1.          0.          2.          1.        ]
 [ 0.          4.          0.          1.          2.        ]
 [ 0.          0.          4.          0.4         0.4       ]
 [ 0.          0.          0.          5.55       -0.7       ]
 [ 0.          0.          0.          0.          4.13963964]]


(c) Use your Gaussian Elimination code to solve $Ax = b$, for some $A,b$

In [3]:
# A and b
A = np.array([[5,1,0,2],[0,4,0,8],[1,1,4,2],[0,1,2,2]])
b = np.array([1,2,3,4])

x, P, LU = ge_pp(A,b)

Input matrix is singular!


#  Question 2

(a)

Since the determinant of an upper triangular matrix is equal to the determinant of its transposed matrix, which is a lower triangular matrix. Therefore, without loss of generality, we only consider the case of the upper triangular matrix. Note for a general upper triangular matrix
$$
\begin{aligned}
\det(A)&=\det\begin{bmatrix}
a_{11}&a_{12}&\cdots&a_{1n}\\
0&a_{22}&\cdots&a_{2n}\\
\vdots&\vdots&\ddots&\vdots&\\
0&0&\cdots&a_{nn}
\end{bmatrix}
=a_{11}\det\begin{bmatrix}
a_{22}&\cdots&a_{2n}\\
\vdots&\ddots&\vdots&\\
0&\cdots&a_{nn}
\end{bmatrix}\\
&=a_{11}a_{22}\det\begin{bmatrix}
a_{33}&\cdots&a_{3n}\\
\vdots&\ddots&\vdots&\\
0&\cdots&a_{nn}
\end{bmatrix}
=\dots=a_{11}a_{22}a_{33}\dots a_{nn}
\end{aligned}
$$

through the expansion of the cofactors. It implies that the determinant of an $n\times n$ upper or lower triangular matrix is equal to the product of its diagonal entries.

(b)

Using the Gaussian Elimination with partial pivoting, we get $PA=LU$ where $P$ is a permutation matrix. Note $\det(P)=-1\;\text{or}\;1$ for different orders, $\det(L)=1$, and $\det(U)$ is equal to the product of the pivots. Thus
$$
\det(PA)=\det(LU)\Rightarrow \det(P)\det(A)=\det(L)\det(U)\Rightarrow\det(U)=-\det(A)\;\text{or}\;\det(A)
$$
that is the product of the pivots in the Gaussian Elimination for $Ax = b$ is equal to the determinant of $A$ up to a sign.

(c)

Directly computing the product of two $n\times n$ lower triangular matrices gives
$$
L_1L_2=\begin{bmatrix}
a_{11}&0&\cdots&0\\
a_{21}&a_{22}&\cdots&0\\
\vdots&\vdots&\ddots&\vdots&\\
a_{n1}&a_{n2}&\cdots&a_{nn}
\end{bmatrix}\begin{bmatrix}
b_{11}&0&\cdots&0\\
b_{21}&b_{22}&\cdots&0\\
\vdots&\vdots&\ddots&\vdots&\\
b_{n1}&b_{n2}&\cdots&b_{nn}
\end{bmatrix}
=\begin{bmatrix}
a_{11}b_{11}&0&\cdots&0\\
\sum^{2}_{k=1}a_{2k}b_{k1}&a_{22}b_{22}&\cdots&0\\
\vdots&\vdots&\ddots&\vdots&\\
\sum^{n}_{k=1}a_{nk}b_{k1}&\sum^{n}_{k=2}a_{nk}b_{k2}&\cdots&a_{nn}b_{nn}
\end{bmatrix}
$$
which is also a $n\times n$ lower triangular matrix. And note $U_1U_2=L_1^TL_2^T=(L_2L_1)^T=U$. Thus the product of two $n\times n$ lower (upper) triangular matrices is a lower (upper) triangular matrix.

(d)

Use the multiplication rule in part (c), we see
$$
\begin{bmatrix}
1\\
&\ddots\\
&&1\\
&&-m_{i+1,i}\\
&&-m_{i+2,i}&\ddots\\
&&\vdots&&\ddots\\
&&-m_{n,i}&&&1\\
\end{bmatrix}\begin{bmatrix}
1\\
&\ddots\\
&&1\\
&&m_{i+1,i}\\
&&m_{i+2,i}&\ddots\\
&&\vdots&&\ddots\\
&&m_{n,i}&&&1\\
\end{bmatrix}=\begin{bmatrix}
1\\
&\ddots\\
&&1\\
&&-m_{i+1,i}+m_{i+1,i}\\
&&-m_{i+2,i}+m_{i+2,i}&\ddots\\
&&\vdots&&\ddots\\
&&-m_{n,i}+m_{n,i}&&&1\\
\end{bmatrix}=I
$$


Thus the inverse of $L_i$ is
$$
L_{i}^{-1}=\begin{bmatrix}
1\\
&\ddots\\
&&1\\
&&m_{i+1,i}\\
&&m_{i+2,i}&\ddots\\
&&\vdots&&\ddots\\
&&m_{n,i}&&&1\\
\end{bmatrix}
$$



# Question 3

Let do the Gaussian Elimination step-by-step
$$
A=\begin{bmatrix}1&0&0\\0&1&0\\0&0&1\\\end{bmatrix}\begin{bmatrix}5&1&0\\0&4&0\\1&4&1\\\end{bmatrix}
=\begin{bmatrix}1&0&0\\0&1&0\\1/5&0&1\\\end{bmatrix}\begin{bmatrix}5&1&0\\0&4&0\\0&19/5&1\\\end{bmatrix}
=\begin{bmatrix}1&0&0\\0&1&0\\1/5&19/20&1\\\end{bmatrix}\begin{bmatrix}5&1&0\\0&4&0\\0&0&1\\\end{bmatrix}
$$

Thus the LU factorization of the matrix $A$ is
$$
A=\begin{bmatrix}1&0&0\\0&1&0\\1/5&19/20&1\\\end{bmatrix}\begin{bmatrix}5&1&0\\0&4&0\\0&0&1\\\end{bmatrix}
$$



# Question 4

Let the matrix $L$ be
$$
L =\begin{bmatrix}l_{11}&0&0\\l_{21}&l_{22}&0\\l_{31}&l_{32}&l_{33}\end{bmatrix}
$$
Then undetermined parameters in the the first column are given by
$$
\begin{bmatrix}l_{11}\\l_{21}\\l_{31}\end{bmatrix}l_{11}=\begin{bmatrix}3\\-1\\0\end{bmatrix}\Rightarrow \begin{bmatrix}l_{11}\\l_{21}\\l_{31}\end{bmatrix}=\begin{bmatrix}\sqrt{3}\\-1/\sqrt{3}\\0\end{bmatrix}
$$
The undetermined parameters in the second column are given by
$$
\begin{bmatrix}l_{22}\\l_{32}\end{bmatrix}l_{22}=\begin{bmatrix}3\\-1\end{bmatrix}-\begin{bmatrix}l_{21}\\l_{31}\end{bmatrix}l_{21}\Rightarrow \begin{bmatrix}l_{22}\\l_{32}\end{bmatrix}=\begin{bmatrix}\sqrt{8/3}\\-\sqrt{3/8}\end{bmatrix}
$$
And the undetermined parameters in the third column are given by
$$
\begin{bmatrix}l_{33}\end{bmatrix}l_{33}=\begin{bmatrix}3\end{bmatrix}-\begin{bmatrix}l_{31}\end{bmatrix}l_{31}-\begin{bmatrix}l_{32}\end{bmatrix}l_{32}\Rightarrow \begin{bmatrix}l_{33}\end{bmatrix}=\begin{bmatrix}\sqrt{21/8}\end{bmatrix}
$$
Thus the Choleski factorization of matrix $A$ is 
$$
A=\begin{bmatrix}\sqrt{3}&0&0\\-1/\sqrt{3}&\sqrt{8/3}&0\\0&-\sqrt{3/8}&\sqrt{21/8}\end{bmatrix}
\begin{bmatrix}\sqrt{3}&-1/\sqrt{3}&0\\0&\sqrt{8/3}&-\sqrt{3/8}\\0&0&\sqrt{21/8}\end{bmatrix}
$$

